apiVersion: apps/v1
kind: Deployment
metadata:
  name: primuslearning
  labels:
    app: primuslearning
spec:
  replicas: 5
  selector:
    matchLabels:
      app: primuslearning
  template:
    metadata:
      labels:
        app: primuslearning
    spec:
      containers:
        - name: primuslearning
          image: 121679896869.dkr.ecr.ap-northeast-1.amazonaws.com/primuslearning:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
