apiVersion: apps/v1
kind: Deployment..
metadata:
  name: pause-pods-prefix
  namespace: other
spec:
  replicas: 300
  selector:
    matchLabels:
      run: pause-pods-prefix
  template:
    metadata:
      labels:
        run: pause-pods-prefix
    spec:
      containers:
      - name: reserve-resources
        image: registry.k8s.io/pause
